### ISSUE TITLE
LIGATURES LIKE "ﬃ" ARE NOT UPPERCASED

### ISSUE THREAD

**Issue by mdarse** [SHOUTCLOUD/SHOUTCLOUD_NODE#2]
HI,
I'M FRENCH AND WE USE "ﬃ" IN SOME WORDS, I WAS UNABLE TO GET THE EXPECTED RESULT OF "FFI". I THINK IT'S A WEB SERVICE ISSUE BUT CAN'T FIND HIS REPOSITORY.

M.

**Comment by joho** [comment]
MOVED OVER TO THE API REPO https://github.com/joho/shoutcloud_api/issues/4
