### ISSUE TITLE
YE_OLD_TO_UPPERCASE result not returned

### ISSUE THREAD

**Issue by sparecycles** [SHOUTCLOUD/SHOUTCLOUD_NODE#5]
Also, that's not how to call it.

This [line](https://github.com/SHOUTCLOUD/SHOUTCLOUD_NODE/blob/62e0a02d1ec5df9be4ba3b8d2eb9475008039fd0/SHOUTCLOUD.js#L36) should be changed to
```javascript
    return YE_OLDE_TO_UPPER_CASE.call(INPUT);
```

**Comment by strugee** [comment]
@SPARECYCLES PERHAPS YOU'D LIKE TO SEND A PULL REQUEST?
